import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/LandingPage/Navbar";
import Footer from "@/components/LandingPage/Footer";

// Load Inter font from Google
const inter = Inter({
  subsets: ["latin"], // Use the "latin" subset for better performance if you only need Latin characters
  variable: "--font-inter",
  display: "swap", // Use font swap for better performance (optional)
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="scroll-smooth">
      <body
        className={`${inter.className}
         antialiased
         flex min-h-screen flex-col 
        `}
      >
        <Navbar />
        <main className="grow">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
